# Generated by Django 4.2.17 on 2025-12-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_at_consent', models.EmailField(blank=True, max_length=254)),
                ('policy_version', models.CharField(default='2025-12-01', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('consent_processing', models.BooleanField()),
                ('consent_delegation', models.BooleanField()),
                ('consent_overseas', models.BooleanField()),
                ('confirm_authority', models.BooleanField()),
                ('consent_medical_responsibility', models.BooleanField()),
                ('is_fully_accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=users.models.consent_pdf_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
