# Generated by Django 4.2.17 on 2025-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='성명'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='position',
            field=models.CharField(blank=True, choices=[('prof', '교수'), ('director', '원장'), ('staff', '봉직의'), ('resident', '전공의'), ('intern', '인턴')], max_length=20, null=True, verbose_name='직위'),
        ),
    ]
