# Generated by Django 4.2.17 on 2025-11-25 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(help_text='사용자가 업로드한 원본 ZIP 파일', upload_to='iolm/zips/')),
                ('result_file', models.FileField(blank=True, help_text='AI 추출 후 생성된 엑셀/CSV 파일', null=True, upload_to='iolm/results/')),
                ('original_filename', models.CharField(max_length=255)),
                ('num_images', models.PositiveIntegerField(blank=True, null=True)),
                ('num_eyes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iolm_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
