# Generated by Django 4.2.17 on 2025-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iolm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='usage_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
