# Generated by Django 4.2.17 on 2025-11-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iolm', '0002_uploadjob_usage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='processed_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='usage_summary',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
