# Generated by Django 4.2.17 on 2025-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iolm', '0004_alter_uploadjob_result_file_alter_uploadjob_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='zip_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
