"""
Django settings for axialis project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from dotenv import load_dotenv
from django.utils.timezone import activate

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
KAKAO_REST_API_KEY = os.getenv("KAKAO_REST_API_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ca1xdj3cw(+mb=w#=+v58$s(kj!wberm21!4qasr9%v_)ad^w2'

# SECURITY WARNING: don't run with debug turned on in production!
## 추후에는 DEBUG FALSE로 바꿔야 함 ****
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "users.CustomUser"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "users",
    "iolm",
    "billing",
    # "storages",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'axialis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ← 이 줄 추가/수정
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axialis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

KAKAO_REST_API_KEY = KAKAO_REST_API_KEY
KAKAO_REDIRECT_URI = 'http://127.0.0.1:8000/users/kakao/callback/'
# KAKAO_REDIRECT_URI = 'https://axialis.ai/users/kakao/callback/'
KAKAO_LOGOUT_REDIRECT_URI = 'http://127.0.0.1:8000/users/logout_complete/'
# KAKAO_LOGOUT_REDIRECT_URI = 'https://axialis.ai/users/logout_complete/'

# Kakao host 상수
KAKAO_AUTH_HOST = "https://kauth.kakao.com"
KAKAO_API_HOST = "https://kapi.kakao.com"

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/users/dashboard/'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"





# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py 맨 아래나 관련 섹션에 추가
IOLM_MAX_UPLOAD_BYTES = 300 * 1024 * 1024  # 200MB


### storage-related


### later, when integrating S3
# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# AWS_ACCESS_KEY_ID = "..."
# AWS_SECRET_ACCESS_KEY = "..."
# AWS_STORAGE_BUCKET_NAME = "axialis-iolm"
# AWS_S3_REGION_NAME = "ap-northeast-2"  # 서울 리전이면 예시

# AWS_S3_SIGNATURE_VERSION = "s3v4"
# AWS_S3_ADDRESSING_STYLE = "virtual"

# AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

# MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"



# Celery 기본 설정
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"  # (선택) 결과 저장

# 타임존/언어에 맞게
CELERY_TIMEZONE = "Asia/Seoul"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 90  # 30분 타임아웃 예시

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "celery": {
            "format": (
                "[{asctime}] [{levelname}] "
                "[{processName}:{process}] "
                "{name} {message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "celery_console": {
            "class": "logging.StreamHandler",
            "formatter": "celery",
        },
        "celery_file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "celery.log"),
            "formatter": "celery",
        },
    },
    "loggers": {
        # iolm.tasks 안에서 logging.getLogger(__name__) 사용
        "iolm.tasks": {
            "handlers": ["celery_console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
