"""
Django settings for axialis project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from dotenv import load_dotenv
from django.utils.timezone import activate
import dj_database_url

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
KAKAO_REST_API_KEY = os.getenv("KAKAO_REST_API_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-only-local")

# SECURITY WARNING: don't run with debug turned on in production!
## 추후에는 DEBUG FALSE로 바꿔야 함 ****
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if origin
]

AUTH_USER_MODEL = "users.CustomUser"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "users",
    "iolm",
    "billing",
    "storages",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

ROOT_URLCONF = 'axialis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ← 이 줄 추가/수정
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axialis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

default_db_url = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

DATABASES = {
    "default": dj_database_url.config(
        default=default_db_url,  # DATABASE_URL 없으면 SQLite로
        conn_max_age=600,
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

KAKAO_REST_API_KEY = KAKAO_REST_API_KEY
KAKAO_REDIRECT_URI = 'http://127.0.0.1:8000/users/kakao/callback/'
# KAKAO_REDIRECT_URI = 'https://axialis.ai/users/kakao/callback/'
KAKAO_LOGOUT_REDIRECT_URI = 'http://127.0.0.1:8000/users/logout_complete/'
# KAKAO_LOGOUT_REDIRECT_URI = 'https://axialis.ai/users/logout_complete/'

# Kakao host 상수
KAKAO_AUTH_HOST = "https://kauth.kakao.com"
KAKAO_API_HOST = "https://kapi.kakao.com"

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/users/dashboard/'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # 나중에 collectstatic용




# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py 맨 아래나 관련 섹션에 추가
IOLM_MAX_UPLOAD_BYTES = 300 * 1024 * 1024  # 200MB


### storage-related

USE_S3_MEDIA = os.getenv("USE_S3_MEDIA") == "1"

if USE_S3_MEDIA:
    # S3 기반 media 저장소
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "ap-northeast-2")

    AWS_DEFAULT_ACL = "private"          # 객체 전부 private
    AWS_S3_FILE_OVERWRITE = False        # 같은 이름이면 새로운 키 사용 (추천)
    AWS_S3_ENCRYPTION = True             # SSE-S3 (AES256) 암호화
    AWS_S3_ADDRESSING_STYLE = "virtual"  # 기본값, 보통 그대로 둠:contentReference[oaicite:1]{index=1}

    # 필요하면 캐시 헤더 등도 추가 가능
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }

    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    # MEDIA_URL 은 굳이 직접 안 써도 되지만, 참고로:
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
    MEDIA_ROOT = None   # S3 사용 시 로컬 media 폴더는 의미 없음
else:
    # 지금까지 쓰던 로컬 media
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"




# Celery 기본 설정
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_DB_BROKER = os.getenv("REDIS_DB_BROKER", "0")
REDIS_DB_RESULT = os.getenv("REDIS_DB_RESULT", "1")

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    os.getenv(
        "REDIS_URL",  # 예: redis://localhost:6379/0 또는 rediss://...
        f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_BROKER}",
    ),
)

CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    os.getenv(
        "REDIS_RESULT_URL",
        f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_RESULT}",
    ),
)

# 타임존/언어에 맞게
CELERY_TIMEZONE = "Asia/Seoul"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 90  # 30분 타임아웃 예시
# Celery가 print/stdout 를 logging 으로 보낼지 여부 (기본 True지만 명시해두는 편이 좋음)
CELERY_WORKER_REDIRECT_STDOUTS = True
CELERY_WORKER_REDIRECT_STDOUTS_LEVEL = "INFO"  # print 도 INFO 로 취급

# Django LOGGING 을 그대로 쓰고 싶으면 추천
CELERY_WORKER_HIJACK_ROOT_LOGGER = False



LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "default": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
        "celery": {
            "format": "[{asctime}] {levelname}/{processName} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        # 터미널 출력용
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },

        # 1) 기존 celery + task 로그용
        "celery_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "celery.log",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "celery",
        },

        # 2) stdout(print) 전용 로그용
        "celery_console_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "celery_console.log",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "celery",
        },
    },

    "loggers": {
        # Django 기본
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },

        "iolm.tasks": {
            "handlers": ["console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },

        # Celery 코어 로그 (worker 시작/종료, task succeed 등)
        "celery": {
            "handlers": ["console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },

        # stdout/stderr 가 redirect 되는 logger
        "celery.redirected": {
            "handlers": ["console", "celery_console_file"],
            "level": "INFO",
            "propagate": False,
        },

        "httpx": {
            # httpx HTTP Request 로그를 stdout 그룹(celery_console.log)에 넣기
            "handlers": ["console", "celery_console_file"],
            "level": "INFO",
            "propagate": False,
        },

        "openai": {
            # 필요하면 OpenAI 라이브러리 로그도 같이 모으기
            "handlers": ["console", "celery_console_file"],
            "level": "INFO",
            "propagate": False,
        },
        # 그 외 루트 logger (원하면 여기에도 celery_file 달 수 있음)
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}


